import Head from 'next/head'
import { Inter, Roboto, Julius_Sans_One } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Header } from '@/components/header'
import Link from 'next/link';
import { IoLocationSharp } from "react-icons/io5";
import { FaUser } from "react-icons/fa";
import { FaArrowDown } from "react-icons/fa";

const julius = Julius_Sans_One({ 
  weight: '400',
  subsets: ['latin'],
});
const roboto = Roboto({ 
  weight: '300',
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Esencia paisa, pues</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <section className={`${styles.home} ${julius.className}`}>
          <Header/>
          <div className={styles.welcome}>
            <h1>ESENCIA PAISA, PUES</h1>
            <p>
              "Medellín es un caleidoscopio de colores y sonidos, 
              cada calle espera ser explorada y contada"
            </p>
            <div>
              <Link href="">GALERIA</Link>
            </div>
          </div>
        </section>

        <section className={styles.about}>
          <h1 className={julius.className}>SOBRE EL PROYECTO</h1>
          <p className={roboto.className} >
            El proyecto "Esencia Paisa, Pues" surge como una iniciativa de un grupo de estudiantes del Politécnico Jaime Isaza Cadavid con el propósito de capturar y resaltar la estética única de la venta y comercio del centro de Medellín. La elección de este tema se fundamenta en el deseo de explorar y mostrar la riqueza cultural y la vida cotidiana que define a esta emblemática zona de la ciudad.
            <br/><br/>
            Medellín, como epicentro cultural y comercial, alberga una gran variedad de puestos y locales que reflejan la identidad paisa. A través de este proyecto, buscamos celebrar y preservar este patrimonio cultural, al tiempo que mostramos la esencia y el carácter vibrante de la ciudad.
            <br/><br/>
            La intención es inmortalizar a través de la fotografía la atmósfera única del comercio en Medellín, capturando la autenticidad, la historia y la diversidad que los define. A través de esta exploración visual, aspiramos a sensibilizar a la comunidad sobre la importancia de estos espacios en la configuración de la identidad local, y fomentar un mayor aprecio por el entorno urbano que nos rodea.
          </p>
        </section>

        <section className={styles.locations}>
          <h1 className={julius.className}>UBICACIONES</h1>
          <section className={roboto.className}>
            <div>
              <IoLocationSharp />
              <Link href="">Centro comercial El Palacio</Link>
            </div>
            <div>
              <IoLocationSharp />
              <Link href="">El hueco</Link>
            </div>
            <div>
              <IoLocationSharp />
              <Link href="">Estación San Antonio</Link>
            </div>
          </section>
        </section>

        <section className={styles.contact}>
          <h1 className={julius.className}>CONTACTO</h1>
          <section className={roboto.className}>
            <div>
              <FaUser />
              <p>Angie Melisa Acevedo Carrillo</p>
            </div>
            <div>
              <FaUser />
              <p>Silvana Gómez Gómez</p>
            </div>
            <div>
              <FaUser />
              <p>Isabella Jurado Blandón</p>
            </div>
            <div>
              <FaUser />
              <p>David Molina Jiménez</p>
            </div>
            <div>
              <FaUser />
              <p>Andres Felipe Pantoja Arias</p>
            </div>
          </section>
        </section>

        <section className={styles.gallery}>
          <h1 className={julius.className}>GALERIA</h1>
          <p className={roboto.className} >
            En el corazón del centro de Medellín, donde las calles bulliciosas y los colores vibrantes convergen, se encuentra un universo de tesoros que capturan la esencia paisa. 
            <br/><br/>
            El proyecto fotográfico "Esencia paisa, pues" nos invita a un viaje visual a través de los mercados locales, donde la vida cotidiana se expresa a través de objetos cuidadosamente seleccionados y presentados.
            <br/><br/>
            La riqueza de la esencia paisa se despliega en cada rincón del mercado. Collares artesanales, tejidos a mano y tesoros tradicionales se exhiben con orgullo. Cada pieza cuenta una historia de habilidad y dedicación, revelando la conexión intrínseca entre el arte local y la identidad paisa. Esta fotografía invita a explorar la herencia cultural a través de los objetos cotidianos que encierran el espíritu vibrante de Medellín.
            <br/><br/>
            A través de estas fotografías, "Esencia paisa, pues" nos invita a apreciar la autenticidad, creatividad y diversidad que se entrelazan en el tejido cultural de Medellín. Cada imagen es más que un simple retrato; es un testimonio visual de cómo la esencia paisa se manifiesta en la vida diaria y en los objetos que dan forma a la identidad de esta ciudad colombiana.
          </p>
          <FaArrowDown />
        </section>
      </div>
      <div className={styles.gallery_container}>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </>
  )
}
